name: GitHub Actions Demo
on: 
  push:
    branches:
      - "main"
    paths-ignore:
      - .github/**
  pull_request:
    branches:
      - "main"
  schedule: 
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "event name is:" ${{ github.event_name }} 
      - run: echo "branch is:" ${{ github.ref }}
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
    
